---
- name: tomcat installation on ubuntu
  hosts: hosts
  become: yes
  vars:
    java_package: openjdk-11-jdk
    tomcat_username: tomcat
    tomcat_home: /opt/tomcat
    tomcat__state: /bin/false
    tomcat_version: '9.0.54'
    tomcat_dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
    tomcat_service_dest: /etc/systemd/system/tomcat.service
    tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
  tasks:
    - name: update package and java installation 
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: adding tomcat user
      ansible.builtin.user:
        name: "{{ tomcat_username }}"
        home: "{{ tomcat_home }}"
        shell: "{{ tomcat__state }}"
        state: present
    - name: download tomcat
      ansible.builtin.get_url:
        url: "{{ tomcat_url }}"
        dest: "{{ tomcat_dest }}"
    - name: untar the file
      ansible.builtin.unarchive:
        src: "{{ tomcat_dest }}"
        dest: "{{ tomcat_home }}"
    - name: create a simlink
      ansible.builtin.file:
        src: "{{ tomcat_home }}"
        state: directory
        owner: "{{ tomcat_username }}"
        group: "{{ tomcat_username }}"
        recursive: yes
    - name: find all the shell files
      find:
        path: "{{ tomcat_home }}/latest/bin"
        pattern: "*.sh"
      register: shfiles
    - set_fact:
        tomcat_excutes: "{{ shfiles.files | map(attribute='path') | list }}"
    - name: changing permissions for shfiles
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 0751
      with_items: "{{ tomcat_excutes }}"
    - name: creating tomcat service file
      ansible.builtin.copy:
        src: tomcat.service
        dest: "{{ tomcat_service_dest }}"
      notify:
        - reload and enable tomcat
    - name: ensure tomcat is running
      ansible.builtin.systemd:
        name: tomcat.service
        state: started
  handlers:
    - name: reload and enable tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: reloaded
        


        
        
      
  